#!/bin/bash
#~~~~~~~~~~
# Generated by cmake from simply-cpp's scripts/deploy.sh.in.
# Edit the template, not this copy: sc_bootstrap.cmake reports when this file has
# drifted, and -DSC_UPDATE_HELPERS=ON puts it back.
#
# Usage: scripts/deploy.sh [server] [user]

module="sc-image"
server="${1:-build}"
user="${2:-root}"
scriptfile=$(realpath "$0")
scriptpath="${scriptfile%/*}"
dirpath=$(realpath "$scriptpath"/..)
echo "Syncing $dirpath to $server:$module"
pushd "$dirpath" || exit
rsync -av ./ "$user@$server:/var/www/build/$module/" --exclude=".git" --exclude=".idea" --exclude="cmake-*" --delete || exit
ssh "$user@$server" "/var/www/build/$module/scripts/run.sh"
popd || exit
