#!/bin/bash
#~~~~~~~~~~
# Generated by cmake from simply-cpp's scripts/run.sh.in.
# Edit the template, not this copy: sc_bootstrap.cmake reports when this file has
# drifted, and -DSC_UPDATE_HELPERS=ON puts it back.
#
# Runs on the server, in the directory deploy.sh synced to.

module="sc-image"
scriptfile=$(realpath "$0")
scriptpath="${scriptfile%/*}"
dirpath=$(realpath "$scriptpath"/..)
echo "Installing $module locally from source in $dirpath"
pushd "$dirpath" || exit
cmake -DCMAKE_BUILD_TYPE=Release -B cmake-build-local -S . || exit
cmake --build cmake-build-local -j 12 || exit
ctest --test-dir cmake-build-local --output-on-failure || exit
cpack --config cmake-build-local/CPackConfig.cmake -G DEB
sudo cmake --install cmake-build-local

popd || exit
