#!/bin/bash
#~~~~~~~~~~
# Generated by cmake from simply-cpp's scripts/run.sh.in.
# Edit the template, not this copy: sc_bootstrap.cmake reports when this file has
# drifted, and -DSC_UPDATE_HELPERS=ON puts it back.
#
# Runs on the server, in the directory deploy.sh synced to.

module="sc-image"
ubuntu_codename=$(lsb_release -sc)
build_directory="cmake-build-$ubuntu_codename"
apt -y install cmake clang-tidy ccache g++

pushd "/var/www/build/$module" || exit
cmake -DCMAKE_BUILD_TYPE=Release -B $build_directory -S . || exit
cmake --build $build_directory -j 12 || exit
ctest --test-dir $build_directory --output-on-failure || exit
cmake --install $build_directory
pushd $build_directory || exit
rm -rf *.deb
cpack --config CPackConfig.cmake -G DEB
rm -rf *unknown*.deb
rm -rf /var/www/build/repo/pool/$ubuntu_codename/*.deb
rsync -av *.deb /var/www/build/repo/pool/$ubuntu_codename/
rm -rf /var/www/build/repo/pool/$ubuntu_codename/*unknown*
export GNUPGHOME=/var/www/build/signing
# reprepro remove noble ...
# reprepro clearvanished
reprepro -b /var/www/build/repo includedeb $ubuntu_codename /var/www/build/repo/pool/$ubuntu_codename/*.deb
# reprepro -b /var/www/build/repo includedeb $ubuntu_codename *.deb
popd || exit

popd || exit
